spring:
  datasource:
    url: jdbc:mysql://121.43.179.233:3306/chenl-server?characterEncoding=utf8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 930224
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 静态资源
  resources:
    static-locations: classpath:web/
  application:
    name: chenl

  # redis
  redis:
    host: 172.30.10.176
    port: 6379
    timeout: 5000ms

mybatis:
  type-aliases-package: com.social.chenl.model
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

server:
  port: 8090
  servlet.context-path: /chenl

logging:
  level:
    root: info
  path: log
  config: classpath:logback-spring.xml

# 此地址由nginx代理，即前端访问http://localhost/rss/ 指向 rss-path
rss-path:
  windowsPath: D:/Temp/chenl/upload/
  linuxPath: /usr/local/chenl/upload/

# 由nginx代理了实际地址，详情搜索资源采集，仅供学习
inc-cnf:
  apiUrl: http://localhost/inc/api